pr/Controllers/CoursController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BEE;
using BLL;
namespace pr.Controllers
{
    public class CoursController : Controller
    {
        private readonly IWebHostEnvironment Environment;
        public CoursController(IWebHostEnvironment webHostEnvironment)
        {
            Environment = webHostEnvironment;
        }
        [Route("Cours")]
        public IActionResult Index()
        {
            var blc = new blcours();
            return View("page_procouct",blc.readall_cours());

        }
        public IActionResult get_skip(int c)
        {
            var blc = new blcours();
            return RedirectToAction(nameof(Index), blc.readall_cours());
            
        }
        public IActionResult cors()
        {
            blteacher blt = new blteacher();
            List<teacher> techers = blt.readall_teacher();
            List<teacher> tt = new List<teacher>();
            foreach (var item in techers)
            {
                if (item.name != null & item.family != null && item.id != 0)
                {
                    tt.Add(item);
                }
            }
            ViewBag.teacher = tt;


            return View("createcours");
        }
        [Route("cours/Addcours")]
        public IActionResult createcours(Models.model.cours cours)
        {
            if (cours != null)
            {
                var blcours = new blcours();
                var bltecher = new blteacher();
                var cours1 = new cours();
                cours1.titel = cours.titel;
                cours1.details = cours.details;
                cours1.time = cours.time;
                cours1.price = cours.price;


                uploadfile up = new uploadfile(Environment);
                string namefolder = "cours";
                cours1.image = up.uploadimage(cours.image, namefolder);
                var namefoldervideo = "cours";
                cours1.video = up.uploadvideo(cours.video, namefoldervideo);

                if (cours.idtechers != null)
                {
                    foreach (var item in cours.idtechers)
                    {
                        if (item != 0)
                        {
                            var teacher = bltecher.serchbynid(Convert.ToInt32(item));

                            cours1.Courss_techers = new List<techer_Cours>();
                            cours1.Courss_techers.Add(new techer_Cours { teacherId = teacher.id, courseId = item });

                        }
                    }
                }
                blcours.create(cours1);
                return RedirectToAction(nameof(getall));
            }
            else
            {
                return null;
            }
        }
        [Route("cours/all")]
        public IActionResult getall()
        {
            var blc = new blcours();
            var list = blc.readall_cours();


            ViewBag.courss = list;
            return View();
        }
        public IActionResult searching(string s)


        {
            var blc = new blcours();
            List<BEE.cours> list = blc.serch(s);
            ViewBag.courss = list;
            return View("getall");
        }
        public Models.model.cours modelcours = new Models.model.cours();
        public IActionResult Edit(int id)
        {

            var blc = new blcours();
            var cours1 = blc.serchbynid(id);



            blteacher blt = new blteacher();
            List<teacher> techers = blt.readall_teacher();
            if (cours1 != null)
            {
                modelcours.id = cours1.id;
                modelcours.details = cours1.details;
                modelcours.time = cours1.time;
                modelcours.price = cours1.price;
                modelcours.videourl = cours1.video;
                modelcours.imagurl = cours1.image;
                modelcours.titel = cours1.titel;
                modelcours.idtechers = cours1.Courss_techers.Select(s => s.Teachers.id).ToList();

            }

            ViewBag.teacher = techers;
            return View(modelcours);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editt(Models.model.cours cours1)
        {

            var blcours = new blcours();
            var becours = new cours();
            var bltecher = new blteacher();
            var beecours = blcours.serchbynid(cours1.id);

            becours.id = cours1.id;
            becours.titel = cours1.titel;
            becours.time = cours1.time;
            becours.price = cours1.price;
            becours.details = cours1.details;

            uploadfile up = new uploadfile(Environment);

            if (cours1.video != null)
            {

                var namefoldervideo = "cours";
                becours.video = up.uploadvideo(cours1.video, namefoldervideo);
            }
            else if (cours1.image != null)
            {
                string namefolder = "cours";
                becours.image = up.uploadimage(cours1.image, namefolder);
            }
            if (cours1.idtechers != null)
            {
                foreach (var item in cours1.idtechers)
                {
                    if (item != 0)
                    {
                        var teacher = bltecher.serchbynid(Convert.ToInt32(item));

                        becours.Courss_techers = new List<techer_Cours>();
                        becours.Courss_techers.Add(new techer_Cours { teacherId = teacher.id, courseId = item });

                    }
                }
            }
            
            blcours.update(becours);
            return RedirectToAction(nameof(getall));
        }
        [Route("Cours/Delet/{id?}")]
        public IActionResult Delet(int id)
        {
            var blc = new blcours();
            var cours1 = blc.serchbynid(id);
            if (cours1 != null)
            {
                blc.delet(id);
            }
            return RedirectToAction(nameof(getall));
        }

        public IActionResult searchCours(int id)
        {
            var blc = new blcours();
            var cours1 = blc.serchbynid(id);
            return View("coursessuser", cours1);
        }
    }
}

pr/Controllers/OrederController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;

using System.Threading.Tasks;
using static pr.Models.model;

namespace pr.Controllers
{
    [Authorize]
    public class OrederController : Controller
    {
        [Route("Addtobasket")]
        public async Task<IActionResult> Addtobasket(int idcours)
        {
            var listbasket = new List<int>();
            if (HttpContext.Session.GetString("basket")!=null)
            {
               listbasket= JsonConvert.DeserializeObject<List<int>>(HttpContext.Session.GetString("basket")).ToList();

            }

            listbasket.Add(idcours);

            HttpContext.Session.SetString("basket", JsonConvert.SerializeObject(listbasket));
            return RedirectToAction("searchCours", "Cours",new { id =idcours});
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

pr/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL;
using BEE;
using Microsoft.AspNetCore.Routing;

namespace pr.Controllers
{
    public class TeacherController : Controller
    {
        private readonly IWebHostEnvironment Environment;
        public TeacherController(IWebHostEnvironment webHostEnvironment)
        {
            Environment = webHostEnvironment;
        }
        //public IActionResult Index()
        //{
        //    return View();
        //}
        [Route("Teacher/creteteacher")]
        public IActionResult creteteacher()
        {
            return View("Techercreate");
        }
        
        [HttpPost]
        public IActionResult create(Models.model.teacher teacher)
        {
            var bltecher = new blteacher();
            var t1 = new teacher();
            t1.name = teacher.name;
            t1.family = teacher.family;
            t1.username = teacher.username;
            t1.password = teacher.pasword;

            uploadfile up = new uploadfile(Environment);
            string namefolder = "teacher";
            t1.image = up.uploadimage(teacher.image, namefolder);
            bltecher.create(t1);
            return RedirectToAction(nameof(read));
        }
        [Route("teachers/all")]
        public IActionResult read()
        {
            var bltecher = new blteacher();

            return View("datatecher", bltecher.readall_teacher());
        }
        [Route("teachers/edit")]
        public async Task<IActionResult> update_data(Models.model.teacher teacher, int id)
        {
            var bltecher = new blteacher();
            var t1 = new teacher();
            t1.id = teacher.id;
            t1.name = teacher.name;
            t1.family = teacher.family;
            t1.email = teacher.email;
            t1.username = teacher.username;
            t1.password = teacher.pasword;
            if (teacher.image!=null)
            {
                uploadfile up = new uploadfile(Environment);
                string namefolder = "teacher";
                t1.image = up.uploadimage(teacher.image, namefolder);

            }
            bltecher.edit(id, t1);
            return RedirectToAction(nameof(read));

        }
        [Route("Delet teacher")]
        public IActionResult delet(int id)
        {
            var bltecher = new blteacher();
            bltecher.delet(id);
            return RedirectToAction(nameof(read));
        }
    }
}

pr/Views/Cours/coursessuser.cshtml
@using Microsoft.AspNetCore.Identity;
@using BEE;
@inject UserManager<User> usermaneger;
@model BEE.cours
@{
    ViewData["Title"] = "coursessuser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section pre{
    <link rel="stylesheet" href="~/esy/css/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="~/esy/css/carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/esy/css/carousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/esy/css/bootstrap/bootstrap-rtl.css">
    <link rel="stylesheet" href="~/esy/css/customcss/style.css">
    <link rel="stylesheet" href="~/esy/css/fontawesome/css/all.css">
}


<div class="container">
    <div class="row">

        <div class="col-md-4 mb-3">
            <img src="~/iamges1/cours/@Model.image" style="width:350px;height:250px" class="img-fluid" alt="@Model.titel">
            <ul class="list-group text-center list-group-flush custom-list-group">
                <li class="list-group-item font-13">عنوان دوره : @Model.titel </li>
                <li class="list-group-item font-13">سطح دوره : مقدماتی تا پیشرفته</li>
                <li class="list-group-item font-13">وضعیت دوره : درحال برگزاری</li>
                <li class="list-group-item font-13">قسمت های ارسالی : @Model.video.Count()</li>
                <li class="list-group-item font-13">قیمت دوره : @Model.price تومان</li>
            </ul>
            <a class="btn btn-block btn-info" asp-action="Addtobasket" asp-controller="Oreder" asp-route-idcours="@Model.id">افزودن به سبد خرید</a>
        </div>


        <div class="col-md-8">
            <div class="card mb-3">
                <div class="card-header bg-white px-0 course-table">
                    <ul class="nav nav-justified pr-0">
                        <li class="nav-item"><a href="" class="nav-link active font-14" data-toggle="list">معرفی دوره</a></li>
                        <li class="nav-item"><a href="" class="nav-link font-14" data-toggle="list">پرسش و پاسخ دوره</a></li>

                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content">
                        <div class="tab-pane active" id="course-info">
                            <!-- Start course info -->

                            <h1 class="teal-text">@Model.titel</h1>

                            <center>
                                <video class="col-12" width="600" height="200" controls="controls">
                                    <source src="~/videos/cours/@Model.video" type="audio/mp4" />
                                </video>
                            </center>

                            <p class="text-justify course-text vazir font-14 my-5">
                                @Model.details
                            </p>

                            <h6 class="mb-3 mt-3">سر فصل ها :</h6>

                            <div class="mb-2 course-items px-2 py-4 d-flex align-items-center product-link">
                                <span class="bg-info count text-center text-white mr-3 font-13">5</span>
                                <span class="mr-3 font-13">هنوز قسمت ها اپلود نشده است</span>
                            </div>







                        </div>
                        <!-- End course info -->

                        <div class="tab-pane fade" id="comment">
                            <!-- Start comment -->

                            <form action="">
                                <div class="row">
                                    <div class="col form-group">
                                        <input type="text" id="name" class="form-control rounded-pill" placeholder="نام خود را وارد کنید ...">
                                    </div>
                                    <div class="col form-group">
                                        <input type="email" id="email" class="form-control rounded-pill" placeholder="ایمیل خود را وارد کنید ...">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <textarea cols="30" rows="10" class="form-control w-100 rounded-lg p-3" placeholder="دیدگاه خود را وارد کنید ..."></textarea>
                                </div>

                                <section class='rating-widget mt-2'>
                                    <!-- star rating-->
                                    <div class='rating-stars'>
                                        <ul id='stars'>
                                            <li class='star' data-tooltip='ضعیف' data-value='1'>
                                                <i class='fa fa-star fa-fw'></i>
                                            </li>
                                            <li class='star' data-tooltip='متوسط' data-value='2'>
                                                <i class='fa fa-star fa-fw'></i>
                                            </li>
                                            <li class='star' data-tooltip='خوب' data-value='3'>
                                                <i class='fa fa-star fa-fw'></i>
                                            </li>
                                            <li class='star' data-tooltip='خیلی خوب' data-value='4'>
                                                <i class='fa fa-star fa-fw'></i>
                                            </li>
                                            <li class='star' data-tooltip='عالی' data-value='5'>
                                                <i class='fa fa-star fa-fw'></i>
                                            </li>
                                        </ul>
                                    </div>
                                </section>

                                <button type="submit" class="btn btn-primary rounded-pill mr-auto d-block font-13">ارسال</button>
                            </form>

                            <div class="bg-light my-3 p-2 pb-4">
                                <div class="d-flex align-items-center">
                                    <p class="text-danger mb-0 vazir font-13">arash</p>
                                    <small class="mx-5 text-muted">15 تیر 1398</small>
                                </div>
                                <p class="text-justify my-2 vazir font-13">آیا آموزش های این دوره تموم شده یا هنوز ادامه داره ؟! </p>

                                <div class=" shadow-sm mr-5 w-75 mt-3 p-2 bg-white">
                                    <div class="d-flex align-items-center">
                                        <p class="text-danger mb-0 vazir font-13">Admin</p>
                                        <small class="mx-5 text-muted">15 تیر 1398</small>
                                    </div>
                                    <p class="text-justify my-2 vazir font-13">سلام بزودی قسمت های جدید آپلود خواهد شد.</p>
                                </div>

                            </div>


                        </div>
                        <!-- End comment -->


                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
@section Scripts{ }

pr/Views/Cours/getall.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "getall";
    Layout = "~/Views/Shared/_Layoutadmin.cshtml";
}
@section pre{
    <link rel="apple-touch-icon" href="~/app-assets/images/favicon/apple-touch-icon-152x152.png">
    <link rel="shortcut icon" type="image/x-icon" href="~/app-assets/images/favicon/favicon-32x32.png">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/vendors.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/flag-icon/css/flag-icon.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/data-tables/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/data-tables/extensions/responsive/css/responsive.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/data-tables/css/select.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/style-rtl.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/themes/vertical-modern-menu-template/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/themes/vertical-modern-menu-template/style.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/pages/data-tables.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/custom/custom.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/dropify/css/dropify.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/sweetalert/sweetalert.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/pages/page-search.min.css">
}



<div class="row">
    <div class="col s12">
        <div class="card">
            <div class="card-content">
                <h4 class="card-title">گزینه های طول صفحه</h4>
                <div id="modal1" class="modal" style="display:none">
                    <div class="modal-content">

                        <div class="col-12">
                            <div id="placeholder" class="card card card-default scrollspy">
                                <div class="card-content">
                                    <h4 class="card-title">فرم ویرایش اطلاعات</h4>
                                    <form asp-controller="Teacher" asp-action="update_data" class="formValidate0" id="edittech" method="post" enctype="multipart/form-data">
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input placeholder="جان دویی" id="fn" type="text" name="name">
                                                <label class="contact-input active" for="name2">نام</label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input placeholder="جان دویی" id="ln" type="text" name="family">
                                                <label class="contact-input active" for="name2">نام خانوادگی</label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input placeholder="" id="em" name="email" type="email">
                                                <label class="contact-input active" for="email"> ایمیل</label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input placeholder="جان دویی" id="un" type="text" name="username">
                                                <label class="contact-input active" for="name2">نام کاربری</label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">

                                                <input placeholder="رمز شما" id="pas" type="password" name="pasword">
                                                <label class="contact-input active" for="password">رمز عبور</label>

                                            </div>

                                            <p>
                                                <label>
                                                    <input type="checkbox" id="chek1" />
                                                    <span>نمایش رمز عبور</span>
                                                </label>
                                            </p>

                                        </div>
                                        <div class="row section">
                                            <div class="col s12 m4 l3">
                                                <p>بارگذاری پروفایل</p>
                                            </div>
                                            <div class="col s12 m8 l9">
                                                <input type="file" id="input-file-now" class="dropify" name="image" data-default-file="" />
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <button class="btn waves-effect waves-light right iransans btnclose" type="submit" name="action">
                                                    ثبت اطلاعات
                                                    <i class="material-icons right">send</i>
                                                </button>
                                            </div>

                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a href="#!" class="modal-action modal-close waves-effect waves-red btn-flat ">مخالف بودن</a>
                    </div>

                </div>
                <div class="row">
                    <div id="search-page" class="section">
                        <div class="row">
                            <div class="col s12">
                                <div id="search-wrapper" class="search card z-depth-0 center-align" >
                                    <div class="card-content pb-0 pl-1 pr-1">
                                        <form asp-action="searching" asp-controller="Cours"  method="get">
                                            <div class="input-field col s12">
                                                <h5>نتایج جستجوی وب سایت</h5>
                                                <input name="s" placeholder="جست و جو"  id="first_name" type="text"  class="search-box validate white search-circle iransans"/>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <h6>مربوط به نتایج جستجوی شما</h6>
                                
                            </div>
                        </div>
                    </div>
                    

                    <div class="col s12">
                        <table class="display">
                            <thead class="col-12">
                                <tr>
                                    <td>عنوان  </td>
                                    <td>زمان دوره (ساعت) </td>
                                    <td>قیمت دوره</td>
                                    <td>ویرایش اطلاعات</td>
                                    <td>حذف اطلاعات </td>

                                </tr>
                            </thead>
                            <tbody class="col-12">
                                @foreach (BEE.cours item in ViewBag.courss)
                                {

                                    <tr>

                                        <td>@item.titel</td>
                                        <td>@item.time</td>
                                        <td>@item.price</td>
                                        <td><a asp-action="Edit" asp-controller="Cours"  asp-route-id="@item.id" id="btn1" class="btn btn-floating btn-large cyan pulse " ><i class="material-icons">edit</i></a></td>
                                        <td><a asp-action="Delet" asp-controller="Cours"  asp-route-id="@item.id" id="btn1" style="color:red" class="btn btn-floating btn-large cyan pulse  " ><i class="material-icons dp48">delete</i></a></td>
                                    </tr>


                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




@section Scripts{
    <script src="~/app-assets/vendors/data-tables/js/jquery.dataTables.min.js"></script>
    <script src="~/app-assets/vendors/data-tables/extensions/responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/app-assets/vendors/data-tables/js/dataTables.select.min.js"></script>
    <script src="~/app-assets/js/scripts/data-tables.min.js"></script>>
    <script src="~/app-assets/js/scripts/advance-ui-modals.min.js"></script>
    <script src="~/app-assets/js/scripts/form-validation.js"></script>
    <script src="~/app-assets/vendors/dropify/js/dropify.min.js"></script>
    <script src="~/app-assets/js-rtl/scripts/form-file-uploads-rtl.min.js"></script>
    <script src="~/app-assets/js-rtl/scripts/extra-components-sweetalert-rtl.min.js"></script>
    <script src="~/app-assets/vendors/sweetalert/sweetalert-rtl.min.js"></script>
    <script src="~/app-assets/js/search.min.js"></script>

}