pr/Controllers/HomeController.cs
using BLL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using pr.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ZarinpalSandbox;

namespace pr.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult contentus()
        {
            return View("contentus");
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult OnlinePayment(int id)
        {
            if (HttpContext.Request.Query["Status"] != "" &&
                HttpContext.Request.Query["Status"].ToString().ToLower() == "ok" &&
                HttpContext.Request.Query["Authority"] != "")
            {
                string authority = HttpContext.Request.Query["Authority"].ToString();
                var blorder = new blorder();
                var o= blorder.serchbyid(id);
               
                var payment = new Payment(o.totalpric);
                var res = payment.Verification(authority).Result;
                if (res.Status == 100)
                {
                    if (HttpContext.Session.GetString("basket") != null)
                    {
                        HttpContext.Session.Clear();
                    }
                    o.statustpayment = true;
                    blorder.update(o);
                    
                    ViewBag.code = res.RefId;
                    return View("Verify");
                }

            }

            return NotFound();
        }
    }
}

pr/ViewComponents/Blogs/BlogsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BEE;
using BLL;

namespace pr.ViewComponents.Courss
{
    public class BlogsViewComponent : ViewComponent
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var blcours = new blblog();

            var liscours = blcours.readall_blog();
            
            return View(liscours);

           
        }

    }
}

pr/ViewComponents/Courss/CourssViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BEE;
using BLL;

namespace pr.ViewComponents.Courss
{
    public class CourssViewComponent : ViewComponent
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var blcours = new blcours();
            var liscours = blcours.readall_cours();
            return View(liscours);
        }

    }
}

pr/ViewComponents/Teachers/TeachersViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BEE;
using BLL;
namespace pr.ViewComponents.Courss.Teacher
{
    public class TeachersViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var blt = new blteacher();
            var listtecher = blt.readall_teacher();
            return View( listtecher);
        }
    }
}

pr/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<!----- Start middle box ----->
<div class="d-none d-md-flex middle-box">
    <div class="container">
        <div class="row d-flex justify-content-end">
            <div class="col-md-6 text-center">
                <h2 class="text-center text-info my-5 pt-3">کسب مهارت های ویژه بازار کار</h2>

                <p class="text-center pt-1 mb-3">
                    کسب و کار شما می‌تواند رشد کند. درآمد شما می‌تواند چند برابر شود.
                    فقط کافی است مسیر درست را بشناسید. کافی است مشتریان خود را در زمان درست،
                    مکان درست و به روش درست هدف قرار دهید. ما در این مسیر همراه شما هستیم.
                </p>

                <a href="#" class="btn py-3 px-4 btn-outline-info mt-4 ml-2" id="btn1">شروع کنید</a>
                <a href="#" class="btn py-3 px-4 mt-4" id="btn2">همه دوره ها</a>

            </div>
        </div>
    </div>
</div>
<!----- End middle box ----->
<!----- Start category box ----->
<div class="container">
    <div class="row my-5">

        <div class="col-md-3 col-sm-6">
            <div class="card box border-0 shadow mb-3" id="box1">
                <img src="images/website-design.png" alt="webdesign" class="my-2 mx-auto d-block">
                <a href="category.html" class="text-center text-white my-2 d-block"> طراحی سایت</a>
            </div>
        </div>

        <div class="col-md-3 col-sm-6">
            <div class="card box border-0 shadow mb-3" id="box2">
                <img src="images/graphic-desig.png" alt="graphic" class="my-2 mx-auto d-block">
                <a href="category.html" class="text-center text-white my-2 d-block">گرافیک</a>
            </div>
        </div>

        <div class="col-md-3 col-sm-6">
            <div class="card box border-0 shadow mb-3" id="box3">
                <img src="images/computing-code.png" alt="code" class="my-2 mx-auto d-block">
                <a href="category.html" class="text-center text-white my-2 d-block">برنامه نویسی وب</a>
            </div>
        </div>

        <div class="col-md-3 col-sm-6">
            <div class="card box border-0 shadow mb-3" id="box4">
                <img src="images/programming.png" alt="programming" class="my-2 mx-auto d-block">
                <a href="category.html" class="text-center text-white my-2 d-block">برنامه نویسی اندروید</a>
            </div>
        </div>

    </div>
</div>
<!----- End category box ----->
<div class="container">
    <div class="row">
        <div class="col-sm-12 d-flex justify-content-between">
            <h6 class="title pb-2">جدیدترین دوره های آموزشی</h6>
        </div>
    </div>
</div>

<div class="text-center">
    @await Component.InvokeAsync("Courss")
</div>


<div class="container d-none d-lg-block">
    <div class="row">
        <div class="col-sm-12 d-flex justify-content-between">
            <h6 class="title pb-2">بهترین مدرسین ما</h6>
        </div>
    </div>
</div>
<!----- Start best teachers ----->
<div class="text-center">
    @await Component.InvokeAsync("Teachers")
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12 d-flex justify-content-between">
            <h6 class="title pb-2">تازه ترین مقالات آموزشی</h6>
        </div>
    </div>
</div>

<!----- Start article boxes ----->
<div class="container">
    <div class="row mt-3 mb-5">
        @await Component.InvokeAsync("Blogs")
    </div>
</div>
<!----- End article boxes ----->

pr/Views/Home/Verify.cshtml
@{
    ViewData["Title"] = "Verify";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Verify</title>
    <link href="~/Content/bootstrap-rtl.css" rel="stylesheet" />
</head>
<body>
    <div>
        @if (ViewBag.IsSuccess == true)
        {
            <div class="alert alert-success">
                <h2>تراکنش با موفقیت انجام شد</h2>
                <hr />
                <p>کد پیگیری شما : @ViewBag.RefId</p>
            </div>
        }
        else
        {
            <div class="alert alert-danger">
                <h2>تراکنش با شکست مواجه شد</h2>
                <hr />
                <p>کد شکست شما : @ViewBag.Status</p>
            </div>
        }
    </div>
</body>
</html>

pr/Views/Home/contentus.cshtml
@{
    ViewData["Title"] = "contentus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container mt-5">
    <div class="row">
        <div class="col-12 mb-3 d-flex justify-content-center align-items-center">
            <h5 class="title pb-2 ">اطلاعات تماس</h5>
        </div>
    </div>
</div>

<div class="container py-4">
    <div class="row">
        <div class="col-sm-4 text-center info">
            <i class="fa fa-phone"></i>
            <p class="mt-3 font-14">09104500086</p>
        </div>

        <div class="col-sm-4 text-center info">
            <i class="fas fa-envelope"></i>
            <p class="mt-3 font-14">mohamadrezakiani9@yahoo.com</p>
        </div>

        <div class="col-sm-4 text-center info">
            <i class="fas fa-map-marker-alt"></i>
            <p class="mt-3 font-14">ایران ,اصفهان</p>
        </div>
    </div>
</div>

<div class="container">
    <div class="row my-5">

        <div class="col-md-6 contact bg-white py-3 shadow-sm mb-3">
            <h6 class="text-info mr-2">ارتباط با ما</h6>
            <p class="text-justify vazir font-14 contact">
                لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده
                از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است.
            </p>

            <form action="" method="">
                <div class="row">
                    <div class="col form-group">
                        <input type="text" id="name" class="form-control rounded-pill" placeholder="نام خود را وارد کنید ...">
                    </div>
                    <div class="col form-group">
                        <input type="email" id="email" class="form-control rounded-pill" placeholder="ایمیل خود را وارد کنید ...">
                    </div>
                </div>
                <div class="form-group">
                    <textarea cols="30" rows="10" class="form-control w-100 rounded-lg p-3" placeholder="پیام خود را وارد کنید ..."></textarea>
                </div>
                <button type="submit" class="btn btn-primary rounded-pill mr-auto d-block font-13">ارسال</button>
            </form>

        </div>

        <div class="col-md-6 mb-3">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3240.50553736921!2d51.37741631474645!3d35.68917533714458!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzXCsDQxJzIxLjAiTiA1McKwMjInNDYuNiJF!5e0!3m2!1sen!2s!4v1596469430690!5m2!1sen!2s"
                    frameborder="0" width="100%" height="550px"></iframe>
        </div>

    </div>
</div>

pr/Views/Home/onlinpy.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["Title"] = "onlinpy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    @ViewBag.code
</div>