pr/Controllers/AdminController.cs
using BLL;
using BEE;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pr.Controllers
{
    public class AdminController : Controller
    {

        private readonly IWebHostEnvironment Environment;
        public AdminController(IWebHostEnvironment webHostEnvironment)
        {
            Environment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View("AdminpageIndex");
        }
        public IActionResult creteteacher()
        {
            return View("Techercreate");
        }
        public void create(Models.model.teacher teacher)
        {
            var bltecher = new blteacher();
            var t1 = new teacher();
            t1.name = teacher.name;
            t1.family = teacher.family;
            t1.username = teacher.username;
            t1.password = teacher.pasword;

            uploadfile up = new uploadfile(Environment);
            string namefolder = "teacher";
            t1.image = up.uploadimage(teacher.image, namefolder);
            bltecher.create(t1);
        }
    }
}

pr/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL;


namespace pr.Controllers
{

    [Authorize]
    public class ProfileController : Controller
    {
        public IActionResult Index(string showbasket, string masege = null)
        {
            ViewBag.showbasket = showbasket;
            if (!string.IsNullOrEmpty(masege))
            {
                ViewBag.successful = masege;
            }
            return View();
        }
       
    }
}

pr/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL;
using BEE;
using Microsoft.AspNetCore.Routing;

namespace pr.Controllers
{
    public class TeacherController : Controller
    {
        private readonly IWebHostEnvironment Environment;
        public TeacherController(IWebHostEnvironment webHostEnvironment)
        {
            Environment = webHostEnvironment;
        }
        //public IActionResult Index()
        //{
        //    return View();
        //}
        [Route("Teacher/creteteacher")]
        public IActionResult creteteacher()
        {
            return View("Techercreate");
        }
        
        [HttpPost]
        public IActionResult create(Models.model.teacher teacher)
        {
            var bltecher = new blteacher();
            var t1 = new teacher();
            t1.name = teacher.name;
            t1.family = teacher.family;
            t1.username = teacher.username;
            t1.password = teacher.pasword;

            uploadfile up = new uploadfile(Environment);
            string namefolder = "teacher";
            t1.image = up.uploadimage(teacher.image, namefolder);
            bltecher.create(t1);
            return RedirectToAction(nameof(read));
        }
        [Route("teachers/all")]
        public IActionResult read()
        {
            var bltecher = new blteacher();

            return View("datatecher", bltecher.readall_teacher());
        }
        [Route("teachers/edit")]
        public async Task<IActionResult> update_data(Models.model.teacher teacher, int id)
        {
            var bltecher = new blteacher();
            var t1 = new teacher();
            t1.id = teacher.id;
            t1.name = teacher.name;
            t1.family = teacher.family;
            t1.email = teacher.email;
            t1.username = teacher.username;
            t1.password = teacher.pasword;
            if (teacher.image!=null)
            {
                uploadfile up = new uploadfile(Environment);
                string namefolder = "teacher";
                t1.image = up.uploadimage(teacher.image, namefolder);

            }
            bltecher.edit(id, t1);
            return RedirectToAction(nameof(read));

        }
        [Route("Delet teacher")]
        public IActionResult delet(int id)
        {
            var bltecher = new blteacher();
            bltecher.delet(id);
            return RedirectToAction(nameof(read));
        }
    }
}

pr/Views/Shared/_Layout.cshtml
@using BEE;
@using Microsoft.AspNetCore.Identity;
@inject UserManager<User> usermaneger;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor IHttpContextAccessor
@using BLL;
@using Newtonsoft.Json;

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> آموزش آنلاین </title>
    <link rel="stylesheet" href="~/esy/css/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="~/esy/css/carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/esy/css/carousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/esy/css/bootstrap/bootstrap-rtl.css">
    <link rel="stylesheet" href="~/esy/css/customcss/style.css">
    <link rel="stylesheet" href="~/esy/css/fontawesome/css/all.css">
    @RenderSection("pre", required: false)
</head>
<body>
    <header class="bg-white">
        <div class="container">
            <div class="row pb-3">

                <div class="d-none d-lg-block col-lg-2">
                    <img src="~/esy/images/logo3.jpg" alt="EasyLearn" title="EasyLearn" class="img-fluid">
                </div>

                <div class="d-none d-lg-flex col-lg-6 align-items-center search-box">
                    <form action="" method="get">
                        <div class="input-group">
                            <input type="search" name="" class="form-control rounded-pill" placeholder="عنوان مورد نظر خود را جستجو کنید ...">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-info rounded-pill font-13">جستجو</button>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="d-none d-lg-flex col-lg-4 align-items-center justify-content-end">
                    @if (User.Identity.IsAuthenticated)
                        {
                            var user = await usermaneger.FindByNameAsync(User.Identity.Name);
                            var coursid = new List<int>();
                            if (IHttpContextAccessor.HttpContext.Session.GetString("basket") != null)
                            {
                                coursid = JsonConvert.DeserializeObject<List<int>>(IHttpContextAccessor.HttpContext.Session.GetString("basket"));
                            }
                            var blcours = new blcours();
                            var courss = blcours.searchbyids(coursid);
                    <div>
                        <a class="cart mt-2 ml-2 dropdown" data-toggle="dropdown">
                            @if (courss.Count() > 0)
                            {
                                <span class="badge badge-info badge-pill">@courss.Count</span><i class="fa fa-shopping-basket"></i>

                            }
                            else if (courss.Count()==0)
                            {
                                <span class="badge badge-info badge-pill">0</span><i class="fa fa-shopping-basket"></i>

                            }

                            <div class="dropdown-menu dropdown-cart mt-3">
                                <ul class="list-unstyled">
                                    @if (courss.Count() > 0)
                                    {
                                        foreach (var item in courss)
                                        {
                                            <li>
                                                <img width="50px" height="50px" src="~/iamges1/cours/@item.image" class="m-1 ml-3">
                                                <div class="float-right">
                                                    <small class=" mt-3 mr-2 d-block">آموزش جامع @item.titel (@item.price تومان)</small>
                                                </div>
                                            </li>

                                        }

                                    }
                                    else if (courss.Count() == 0)
                                    {
                                        <li>
                                            
                                            <div class="float-right">
                                                <small class=" mt-3 mr-2 d-block">هیچ محصولی انتخاب نشده است </small>
                                            </div>
                                        </li>
                                    }
                                    <li>
                                        <a asp-controller="Profile" asp-action="index" asp-route-showbasket="active" type="button" class="btn btn-outline-success"> پرداخت</a>
                                        <div class="float-right">

                                            <small class=" mt-3 mr-2 d-block">قیمت کل :@courss.Sum(i => i.price) تومان</small>
                                        </div>
                                    </li>


                                </ul>
                            </div>
                            <div class="dropdown-menu dropdown-cart mt-3">
                                <a asp-controller="Profile" asp-action="index" asp-route-showbasket="active" class="btn btn-primary">پنل کاربری <span class="glyphicon glyphicon-user"></span></a>
                            </div>
                        </a>
                        <div class="container left">
                            <a asp-controller="Profile" asp-action="index" asp-route-showbasket="active" class="btn btn-primary">پنل کاربری <span class="glyphicon glyphicon-user"></span></a>
                        </div>
                        
                    </div>

                    }
                    else
                    {
                        <a href="@Url.Action("Register","Account")" class="btn btn-outline-info font-13 vazir-med-fa"><i class="fa fa-user-plus pl-1"></i>ثبت نام</a>
                        <a href="@Url.Action("Login","Account")" class="btn btn-info font-13 vazir-med-fa mx-2">ورود</a>

                    }

                </div>

            </div>

            <div class="row">
                <!----- Start mobile header ----->

                <div class="col-12 d-flex d-lg-none justify-content-center">
                    <img src="images/logo.jpg" alt="Easylearn">
                </div>

                <div class="col-12 d-flex d-lg-none justify-content-center mb-4 mobile-header">
                    <a href="@Url.Action("Register","Account")" class="border-left ml-3"><i class="fa fa-user-plus ml-3"></i></a>
                    <a href="@Url.Action("Login","Account")" class="border-left ml-3"><i class="fa fa-lock ml-3"></i></a>
                    <a href="#" data-toggle="collapse"><i class="fa fa-search"></i></a>
                  

                </div>

                <div id="search" class=" d-lg-none col-10 mx-auto collapse mb-4 justify-content-center">
                    <form action="">
                        <div class="input-group">
                            <input type="search" name="" class="form-control rounded-pill" placeholder="عنوان مورد نظر خود را جستجو کنید ...">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-info rounded-pill font-13">جستجو</button>
                            </div>
                        </div>
                    </form>
                </div>
               

            </div><!----- End mobile header ----->
        </div>
    </header>
    <!----- Start menu ----->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm sticky-top">

        <div class="container">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#mainmenu">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="mainmenu">
                <ul class="navbar-nav pr-0 custom-navbar font-14 text-center">
                    <li class="nav-item ml-3 custom-nav-item"><a href="@Url.Action("index","Home")" class="nav-link">صفحه اصلی</a></li>
                    <li class="nav-item ml-3 custom-nav-item"><a href="@Url.Action("Index","Cours")" class="nav-link">دوره های اموزشی</a></li>
                    <li class="nav-item ml-3 custom-nav-item"><a href="@Url.Action("readall_forclient","Blog")" class="nav-link">بلاگ</a></li>
                    <li class="nav-item ml-3 custom-nav-item"><a href="@Url.Action("contentus","Home")" class="nav-link">تماس باما</a></li>
                </ul>
            </div>
        </div>

    </nav>
    <!----- End menu ----->

    <div class="container">


        @RenderBody()


    </div>

    <footer class="bg-white">
        <div class="container py-2">
            <div class="row">

                <div class="col-md-4">
                    <img src="images/logo4.jpg" alt="" class="img-fluid">
                    <p class="text-justify font-14 vazir mb-4">
                        خیلی راحت میتونی برنامه نویسی رو شروع کنی پس معطلش نکن
                    </p>
                    <p class="font-14"><i class="fas fa-map-marker-alt text-muted ml-2"></i> ایران ,اصفهان</p>
                    <p class="font-14"><i class="fas fa-envelope text-muted ml-2"></i> mohamdrezakiani9@yahoo.com</p>
                    <p class="font-14"><i class="fa fa-phone text-muted ml-2"></i>0910-4500086</p>
                </div>

                <div class="col-md-2 text-center footer-links">
                    <span class="mt-5 mb-3 d-block font-14">دسترسی سریع</span>
                    <ul class="list-unstyled">
                        <li class="my-3"><a href="#">درباره ما</a></li>
                        <li class="my-3"><a href="#">تماس با ما</a></li>

                    </ul>
                </div>

                <div class="col-md-2 text-center footer-links">
                    <span class="mt-5 mb-3 d-block font-14">لینک های مفید</span>
                    <ul class="list-unstyled">
                        <li class="my-3"><a href="#">حساب کاربری</a></li>
                    </ul>
                </div>

                <div class="col-md-4 search-box text-center">
                  
                    <div class="mt-5 social-media">
                        <a href="#"><i class="fab fa-instagram p-1" id="instagram"></i></a>
                        <a href="#"><i class="fab fa-twitter bg-info p-1"></i></a>
                        <a href="#"><i class="fab fa-youtube bg-danger p-1"></i></a>
                        <a href="#"><i class="fab fa-telegram bg-primary p-1"></i></a>
                    </div>
                </div>

            </div>


            <div class="row justify-content-end">
                <a class="topbutton"> <i class="fa fa-chevron-circle-up"> </i> </a>
            </div>


            <div class="row">
                <div class="col-12 text-center">
                    <hr>
                    <p class="text-muted font-14"> کلیه حقوق این سایت متعلق به تیم برنامه نویسی کیان کد می باشد </p>
                </div>
            </div>

        </div>
    </footer>

    <script src="~/esy/js/jquery-3.3.1.min.js"></script>
    <script src="~/esy/js/popper.min.js"></script>
    <script src="~/esy/js/bootstrap.min.js"></script>
    <script src="~/esy/js/owl.carousel.min.js"></script>
    <script src="~/esy/js/myscript.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

pr/Views/Shared/_Layoutadmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google.">
    <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template, eCommerce dashboard, analytic dashboard">
    <meta name="author" content="ThemeSelect">
    <title>مدیریت وبسایت </title>
    <link rel="apple-touch-icon" href="~/app-assets/images/favicon/apple-touch-icon-152x152.png">
    <link rel="shortcut icon" type="image/x-icon" href="~/app-assets/images/favicon/favicon-32x32.png">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- BEGIN: VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/vendors.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/animate-css/animate.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/chartist-js/chartist.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/chartist-js/chartist-plugin-tooltip.css">
    <!-- END: VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/style-rtl.min.css">
    <!-- BEGIN: Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/themes/vertical-modern-menu-template/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/themes/vertical-modern-menu-template/style.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/pages/dashboard-modern.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/pages/intro.min.css">
    <!-- END: Page Level CSS-->
    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/custom/custom.css">
    <!-- END: Custom CSS-->
    @RenderSection("pre", required: false)
</head>
<body class="vertical-layout vertical-menu-collapsible page-header-dark vertical-modern-menu preload-transitions 2-columns   " data-open="click" data-menu="vertical-modern-menu" data-col="2-columns">
    <header class="page-topbar" id="header">
        <div class="navbar navbar-fixed">
            <nav class="navbar-main navbar-color nav-collapsible sideNav-lock navbar-dark gradient-45deg-indigo-purple no-shadow">
                <div class="nav-wrapper">
                    <div class="header-search-wrapper hide-on-med-and-down">
                        <i class="material-icons">search</i>
                        <input class="header-search-input z-depth-2 iransans" type="text" name="Search" placeholder="جست و جو..." data-search="template-list">
                        <ul class="search-list collection display-none"></ul>
                    </div>
                    <ul class="navbar-list right">
                        
                        <li class="hide-on-large-only search-input-wrapper"><a class="waves-effect waves-block waves-light search-button" href="javascript:void(0);"><i class="material-icons">search</i></a></li>
                        
                        @*<li><a class="waves-effect waves-block waves-light profile-button" href="javascript:void(0);" data-target="profile-dropdown"><span class="avatar-status avatar-online"><img src="~/app-assets/images/avatar/avatar-7.png" alt="avatar"><i></i></span></a></li>*@
                        
                    </ul>
                    <!-- translation-button-->
                    <!-- translation-button-->
                    <ul class="dropdown-content" id="translation-dropdown">
                        <li class="dropdown-item"><a class="grey-text text-darken-1" href="#!" data-language="en"><i class="flag-icon flag-icon-ir"></i> فارسی</a></li>
                        <li class="dropdown-item"><a class="grey-text text-darken-1" href="#!" data-language="en"><i class="flag-icon flag-icon-gb"></i> انگلیسی</a></li>
           
                        
                    </ul>
                </div>
                <nav class="display-none search-sm">
                    <div class="nav-wrapper">
                        <form id="navbarForm">
                            <div class="input-field search-input-sm">
                                <input class="search-box-sm" type="search" required="" id="search" placeholder="Explore Materialize" data-search="template-list">
                                <label class="label-icon" for="search"><i class="material-icons search-sm-icon">search</i></label><i class="material-icons search-sm-close">close</i>
                                <ul class="search-list collection search-list-sm display-none"></ul>
                            </div>
                        </form>
                    </div>
                </nav>
            </nav>
        </div>

    </header>
    <!-- END: Header-->
    <!-- BEGIN: SideNav-->
    <aside class="sidenav-main nav-expanded nav-lock nav-collapsible sidenav-light sidenav-active-square">
        <div class="brand-sidebar">
            <h1 class="logo-wrapper">
                <a class="brand-logo darken-1" href="#">
                    <img class="hide-on-med-and-down" src="~/app-assets/images/logo/materialize-logo-color.png" alt="materialize logo" />
                </a><a class="navbar-toggler" href="#"><i class="material-icons">radio_button_checked</i></a>
            </h1>
        </div>
        <ul class="sidenav sidenav-collapsible leftside-navigation collapsible sidenav-fixed menu-shadow" id="slide-out" data-menu="menu-navigation" data-collapsible="menu-accordion">

            <li class="navigation-header">
                <a class="navigation-header-text">داشبورد </a><i class="navigation-header-icon material-icons">more_horiz</i>
            </li>
            <li class="bold">
                <a class="waves-effect waves-cyan " href="@Url.Action("index","Admin")"><span class="material-icons-sharp"> صفحه اصلی </span> </a>
            </li>
            <li class="bold">
                <a class="waves-effect waves-cyan " href="@Url.Action("read","Teacher")"><span class="material-icons-sharp"> اساتید </span> </a>
            </li>
            <li class="bold">
                <a class="waves-effect waves-cyan " href="@Url.Action("creteteacher","Teacher")"><span class="material-icons-sharp"> ثبت استاد </span> </a>
            </li>
            <li class="bold">
                <a class="waves-effect waves-cyan " href="@Url.Action("cors","Cours")"><span class="menu-title"> ثبت دوره جدید  </span></a>
            </li>
            <li class="bold">
                <a class="waves-effect waves-cyan " href="@Url.Action("getall","Cours")"><span class="menu-title"> لیست دوره ها  </span></a>
            </li>
            <li class="bold">

                <a class="waves-effect waves-cyan " href="@Url.Action("create","Blog")"> <span class="menu-title" data-i18n="Mail">مقاله نویسی </span></a>
                <a class="waves-effect waves-cyan " href="@Url.Action("readall","Blog")"> <span class="menu-title" data-i18n="Mail">مقالات  </span></a>
            </li>


        </ul>
        <div class="navigation-background"></div><a class="sidenav-trigger btn-sidenav-toggle btn-floating btn-medium waves-effect waves-light hide-on-large-only" href="#" data-target="slide-out"><i class="material-icons">menu</i></a>
    </aside>
    <!-- END: SideNav-->
    <div class="container">
        <div id="main">

            @RenderBody()

        </div>
    </div>
    <footer class="page-footer footer footer-static footer-dark gradient-45deg-indigo-purple gradient-shadow navbar-border navbar-shadow">
        <div class="footer-copyright">
            <div class="container">
                <span>
                    &copy; 2020 <a href="#" target="_blank">تیم برنامه نویسی کیان کد</a>
                    تمامی حقوق محفوظ است.
                </span>
            </div>
        </div>
    </footer>>
    <script src="~/app-assets/js/vendors.min.js"></script>
    <script src="~/app-assets/vendors/chartjs/chart.min.js"></script>
    <script src="~/app-assets/vendors/chartist-js/chartist.min.js"></script>
    <script src="~/app-assets/vendors/chartist-js/chartist-plugin-tooltip.js"></script>
    <script src="~/app-assets/vendors/chartist-js/chartist-plugin-fill-donut.min.js"></script>
    <script src="~/app-assets/js/plugins.min.js"></script>
    <script src="~/app-assets/js/search.min.js"></script>
    <script src="~/app-assets/js-rtl/custom/custom-script-rtl.min.js"></script>
    <script src="~/app-assets/js/scripts/customizer.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>